name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: install
      run: pip install pathspec
    - name: format
      run: ./scripts/clang_format.py --no-write

  coverage:
    needs: [lint]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shannonbooth'
    steps:
    - uses: actions/checkout@v6
    - name: install gcovr
      run: sudo apt-get update -qy
        && sudo apt-get install gcovr -qy
    - name: configure
      run: cmake -DBUILD_TESTING=on -DPATCH_ENABLE_COVERAGE=yes -DPATCH_WARNINGS_AS_ERRORS=on -S . -B build
    - name: compile
      run: cmake --build build -j2
    - name: test
      run: ctest --test-dir build --output-on-failure -j2
    - name: coverage
      run: cmake --build build --target coverage
    - name: submit to codecov.io
      uses: codecov/codecov-action@v3
      with:
        files: ./build/coverage.xml

  build:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v6
    - name: configure
      run: cmake -DBUILD_TESTING=on -DPATCH_WARNINGS_AS_ERRORS=on -S . -B build
    - name: compile
      run: cmake --build build -j2
    - name: test
      run: ctest --test-dir build --output-on-failure -C Debug -j2

  mingw:
    needs: [lint]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v6
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja
    - name: configure
      run: cmake -G Ninja -DBUILD_TESTING=on -DPATCH_WARNINGS_AS_ERRORS=on -S . -B build
    - name: compile
      run: cmake --build build -j2
    - name: test
      run: ctest --test-dir build --output-on-failure -j2
